spring:
  main:
    web-application-type: none
  application:
    name: sanparser
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: sanparser
santech:
  catalog-uri: file:/C:/Users/Supcheg/in/santech_catalog.xml
  associations:
    analogues-uri: https://www.santech.ru/catalog/getVariantAnalogFull/
    associations-uri: https://www.santech.ru/catalog/getVariantAssoc/
sanparser:
  mode: categories